config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")

  resources :associations, :funders

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/association.rb
class Association < ApplicationRecord
#    attr_accessor :name, :website, :logo_address
  validates :name, presence: true
  validates :website, presence: true#, length: { minimum: 10 }
  validates :logo_address, presence: true#, length: { minimum: 10 }
end

app/models/funder.rb
class Funder < ApplicationRecord
#    attr_accessor :name, :website, :logo_address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/associations_controller.rb
class AssociationsController < ApplicationController
    def index
        @associations = Association.all
    end

    def show
        @association = Association.find(params[:id])
    end

    def new
        @association = Association.new
    end

    def create
        @association = Association.new(association_params)

        if @association.save
            redirect_to @association
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @association = Association.find(params[:id])
    end

    def update
        @association = Association.find(params[:id])
        if @association.update(association_params)
            redirect_to @association
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @association = Association.find(params[:id])
        @association.destroy
        redirect_to root_path, status: :see_other
    end

    private
    def association_params
        params.require(:association).permit(:name, :website, :logo_address)
    end
end

app/controllers/funders_controller.rb
class FundersController < ApplicationController
    def index
        @funders =Funder.all
    end
    def show
        @funder = Funder.find(params[:id])
    end

    def new
        @funder = Funder.new
    end

    def create
        @funder = Funder.new(funder_params)

        if @funder.save
            redirect_to @funder
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @funder = Funder.find(params[:id])
    end

    def update
        @funder = Funder.find(params[:id])
        if @funder.update(funder_params)
            redirect_to @funder
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @funder = Funder.find(params[:id])
        @funder.destroy
        redirect_to root_path, status: :see_other
    end

    private
    def funder_params
        params.require(:funder).permit(:name, :website, :logo_address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associations_helper.rb
module AssociationsHelper
end

app/helpers/funders_helper.rb
module FundersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/associations/_form.html.erb
<%= form_with model: association do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% association.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :website %><br>
    <%= form.text_area :website %>
    <% association.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :logo_address %><br>
    <%= form.text_area :logo_address %>
    <% association.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/associations/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", association: @association %>

app/views/associations/index.html.erb
<h2>Associations</h2>

<%= link_to "New Association", new_association_path, class:"bouton" %>
<ul>
  <% @associations.each do |association| %>
    <li>
        <% if association.logo_address.present? %>
          <%= image_tag(association.logo_address, width: '100') %>
        <% end %>
        <%= link_to association.name, association %>
    </li>
  <% end %>
</ul>

app/views/associations/new.html.erb
<h1>New Association</h1>

<%= render "form", association: @association %>

app/views/associations/show.html.erb
<h1><%= @association.name %></h1>
<%= image_tag(@association.logo_address, width: '100') if @association.logo_address.present? %>
<p><%= link_to "website", @association.website, class:"bouton" %></p>
<ul>
  <li><%= link_to "Edit", edit_association_path(@association), class:"bouton" %></li>
  <li><%= link_to "Destroy", association_path(@association), class:"bouton", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/funders/_form.html.erb
<%= form_with model: funder do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% funder.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :website %><br>
    <%= form.text_area :website %>
    <% funder.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :logo_address %><br>
    <%= form.text_area :logo_address %>
    <% funder.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funders/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", funder: @funder %>

app/views/funders/index.html.erb
<h2>Funders</h2>

<table>
  <thead>
    <tr>
      <th>Logo</th>
      <th>Nom</th>
    </tr>
  </thead>
  <tbody>
    <% @funders.each do |funder| %>
      <tr>
        <td><%= image_tag(funder.logo_address, width: '100') if funder.logo_address.present? %></td>
        <td><%= link_to funder.name, funder %></td>
      </tr>
    <% end %>
  <%= link_to "New Funder", new_funder_path, class:"bouton" %>
  </tbody>
</table>

app/views/funders/new.html.erb
<h1>New Funder</h1>

<%= render "form", funder: @funder %>

app/views/funders/show.html.erb
<h1><%= @funder.name %></h1>
<%= image_tag(@funder.logo_address, width: '100') if @funder.logo_address.present? %>
<p><%= link_to "website", @funder.website, class:"bouton" %></p>
<ul>
  <li><%= link_to "Edit", edit_funder_path(@funder), class:"bouton" %></li>
  <li><%= link_to "Destroy", funder_path(@funder), class:"bouton", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yabonlapub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'pages/header' %>
    <%= yield %>
    <%= render 'pages/footer' %>
  </body>
</html>

app/views/pages/_footer.html.erb
<br>
<footer>
    <p>&copy; 2024 Yabonlapub. Tous droits réservés.</p>
</footer>

app/views/pages/_header.html.erb
<header>
    <nav class="main-nav">
        <ul>
            <%= link_to image_tag("logo.png", size: "15x15"), root_path %> <!-- classe definie dans assets en css -->
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Associations', associations_path %></li>
            <li><%= link_to 'Funders', funders_path %></li>
            <% if user_signed_in? %>
                <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: "delete" } %></li>
                <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <% else %>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
            <% end %>
        </ul>
    </nav>
<!-- https://stackoverflow.com/questions/32444342/devise-flash-message-being-notice -->
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <% flash.each do |type, msg| %>
                <% if type == "notice" %>
                    <div class="notice">
                <% else %>
                    <div class="alert">
                <% end %>
                <ul>
                    <li>
                        <%= msg %>
                    </li>
                </ul>
                </div>
            <% end %>
        </div>
    </div>
</header>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yabonlapub</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <main>
        <%= yield %>
    </main>
</body>
</html>